/* TheFlap Challenges + Store (self-contained, v1) */
(function(){
if(window.__flapCS2)return;window.__flapCS2=1;
function u(){try{if(window.ME&&ME.name)return ME.name;}catch(e){}try{var m=JSON.parse(localStorage.getItem('flap_me')||'{}');if(m&&m.name)return m.name;}catch(e){}return localStorage.getItem('flap_lastname')||'';}
function sb(){return window.sb;}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function comma(n){var s=''+(n||0);var o='',c=0;for(var i=s.length-1;i>=0;i--){o=s[i]+o;if(++c%3===0&&i>0)o=','+o;}return o;}
var BAL=0,OWNED={},EQUIP={},ITEMS=[],CUR=null,SUBS=[],LIKES={},MINE={},MAXLEN=30,TAB='chal';
var EMO={emoji_laugh:'&#128514;',emoji_smirk:'&#128527;',emoji_100:'&#128175;',emoji_shock:'&#128561;',emoji_fire:'&#128293;',emoji_pleading:'&#129402;',rainbow_name:'&#127752;',name_chrome:'&#9881;',name_gold:'&#11088;',name_galaxy:'&#127756;',name_fire:'&#128293;',name_lava:'&#127755;',name_neon:'&#128161;',name_ocean:'&#127754;',name_ice:'&#10052;',name_toxic:'&#9763;',name_sunset:'&#127749;',name_bubble:'&#128173;',name_glow:'&#10024;',name_shadow:'&#127761;',name_color:'&#127912;',gold_frame:'&#128993;',frame_galaxy:'&#127756;',badge_vip:'&#127941;',boost_spotlight:'&#10024;',pinaflap:'&#128204;'};
var FX={rainbow_name:'fx-rainbow',name_chrome:'fx-chrome',name_gold:'fx-gold',name_galaxy:'fx-galaxy',name_fire:'fx-fire',name_lava:'fx-lava',name_neon:'fx-neon',name_ocean:'fx-ocean',name_ice:'fx-ice',name_toxic:'fx-toxic',name_sunset:'fx-sunset',name_bubble:'fx-bubble',name_glow:'fx-glow',name_shadow:'fx-shadow'};
var CATS=['Moods','Names','Frames','Badges','Boosts'];
var st=document.createElement('style');st.textContent='.fx-rainbow{background:linear-gradient(90deg,#ff5e5e,#ffb14e,#ffee56,#5efc82,#5ec8ff,#b18cff,#ff5e5e);background-size:300% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxflow 4s linear infinite}@keyframes fxflow{to{background-position:300% 0}}.fx-chrome{background:linear-gradient(90deg,#8a8a8a,#f5f5f5,#c0c0c0,#f5f5f5,#8a8a8a);background-size:250% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxflow 3s linear infinite}.fx-gold{background:linear-gradient(90deg,#a67c00,#ffd75e,#fff3b0,#ffd75e,#a67c00);background-size:250% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxflow 3.2s linear infinite}.fx-galaxy{background:linear-gradient(90deg,#7b2ff7,#4a86ff,#b06ab3,#7b2ff7);background-size:260% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxflow 5s linear infinite}.fx-fire{background:linear-gradient(0deg,#ff3d00,#ff9e00,#ffd000);-webkit-background-clip:text;background-clip:text;color:transparent}.fx-lava{background:linear-gradient(90deg,#3a0ca3,#f72585,#ff9e00);background-size:260% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxflow 4s linear infinite}.fx-neon{color:#39ff14;text-shadow:0 0 4px #39ff14,0 0 10px #39ff14}.fx-ocean{background:linear-gradient(90deg,#00c6ff,#0072ff,#00e5c0,#00c6ff);background-size:260% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;animation:fxflow 5s linear infinite}.fx-ice{background:linear-gradient(90deg,#7fdbff,#e0fbff,#9ad0ff);background-size:220% 100%;-webkit-background-clip:text;background-clip:text;color:transparent;text-shadow:0 0 6px rgba(150,220,255,.4)}.fx-toxic{color:#aaff00;text-shadow:0 0 6px rgba(140,255,0,.7)}.fx-sunset{background:linear-gradient(90deg,#ff6a3d,#ff2e8b,#ffb14e);-webkit-background-clip:text;background-clip:text;color:transparent}.fx-bubble{background:linear-gradient(90deg,#ff8fd6,#ff5ea8,#ffa6e0);-webkit-background-clip:text;background-clip:text;color:transparent}.fx-glow{color:#ff8a00;text-shadow:0 0 8px #ffcf6a}.fx-shadow{color:#cfcfe0;text-shadow:2px 2px 0 rgba(0,0,0,.6)}';
document.head.appendChild(st);
function loadAll(cb){var c=sb();if(!c){cb&&cb();return;}var uu=u();var n=0;function d(){n++;if(n>=4)cb&&cb();}
 c.from('flap_feathers').select('balance').eq('name',uu).maybeSingle().then(function(r){BAL=(r.data&&r.data.balance)||0;d();},function(){d();});
 c.from('flap_store_items').select('item,category,label,price,sort').order('sort',{ascending:true}).then(function(r){ITEMS=r.data||[];d();},function(){d();});
 c.from('flap_store_owned').select('item').eq('name',uu).then(function(r){OWNED={};(r.data||[]).forEach(function(o){OWNED[o.item]=1;});d();},function(){d();});
 c.from('flap_equipped').select('slot,item').eq('name',uu).then(function(r){EQUIP={};(r.data||[]).forEach(function(o){EQUIP[o.slot]=o.item;});d();},function(){d();});
}
var ov=document.createElement('div');ov.id='fcs2';
ov.style.cssText='position:fixed;inset:0;z-index:2147483000;background:radial-gradient(circle at 20% 0%,#241a33,transparent 45%),#14101c;display:none;overflow:auto;color:#eee;font-family:inherit';
function balPill(){return '<span style="margin-left:auto;background:#fff;color:#c8730a;font-weight:800;border-radius:999px;padding:6px 12px;font-size:14px">&#129718; '+comma(BAL)+'</span>';}
function tabBtn(id,label){var on=TAB===id;return '<button data-tab="'+id+'" class="fcTab" style="border:0;border-radius:10px;font-weight:800;font-size:14px;padding:8px 13px;cursor:pointer;'+(on?'background:linear-gradient(180deg,#ffcf5a,#f0a91c);color:#3a2600':'background:transparent;color:#cdbfe8')+'">'+label+'</button>';}
function head(){return '<div style="position:sticky;top:0;background:#1b1630;border-bottom:1px solid #2c2444;display:flex;align-items:center;gap:8px;padding:10px 12px;z-index:5">'+tabBtn('chal','&#127942; Challenges')+tabBtn('store','&#129718; Store')+balPill()+'<button id="fcX" style="margin-left:6px;background:0;border:0;color:#cbb98f;font-size:26px;line-height:1;cursor:pointer">&times;</button></div>';}
function render(){ov.innerHTML=head()+'<div id="fcBody" style="max-width:540px;margin:0 auto;padding:16px 14px 60px">'+(TAB==='chal'?chalHtml():storeHtml())+'</div>';bind();}
function open(){TAB='chal';ov.style.display='block';render();loadAll(function(){render();chalLoad();applyCos();});}
function close(){ov.style.display='none';}
function bind(){[].forEach.call(ov.querySelectorAll('.fcTab'),function(b){b.onclick=function(){TAB=b.getAttribute('data-tab');render();if(TAB==='chal')chalLoad();};});var x=document.getElementById('fcX');if(x)x.onclick=close;if(TAB==='chal')chalBind();else storeBind();}
window.flapPanel=open;window.flapChallenge=open;
function lc(id){return LIKES[id]||0;}
function chStep(ic,l){return '<div style="background:#1c150c;border:1px solid #3a2c18;border-radius:12px;padding:12px 5px;text-align:center"><div style="font-size:20px">'+ic+'</div><div style="color:#e7c98c;font-size:10.5px;font-weight:700;margin-top:4px">'+l+'</div></div>';}
function chalHtml(){var h='<div style="text-align:center;background:linear-gradient(135deg,#3a2b6e,#5a3ea0 60%,#7a52c8);border-radius:16px;padding:16px 14px;margin-bottom:12px;color:#fff;font-family:Fredoka,sans-serif;letter-spacing:.3px"><div style="font-weight:700;font-size:22px">&#127942; TheFlap Challenges</div><div style="color:#e5dbff;font-size:13.5px;margin-top:3px;font-weight:500">Show up, show out &#8212; win Feathers.</div></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:14px">'+chStep('&#127916;','Join a challenge')+chStep('&#128247;','Drop a video')+chStep('&#127942;','Climb the board')+'</div><div style="color:#fff;font-weight:800;font-size:15px;margin:2px 2px 10px">&#128293; Available now</div>';
 if(!CUR){h+='<div style="color:#b9a88a;text-align:center;padding:26px">No active challenge right now. Check back soon!</div>';return h;}
 var sorted=SUBS.slice().sort(function(a,b){return lc(b.id)-lc(a.id);});
 h+='<div style="background:#241a10;border:1px solid #3a2c18;border-radius:14px;padding:13px 14px;margin-bottom:12px"><div style="font-family:Fredoka,sans-serif;font-weight:700;color:#fff;font-size:17px">&#127942; '+esc(CUR.title)+'</div><div style="color:#e7c98c;font-size:13px;line-height:1.5;margin-top:4px">'+esc(CUR.prompt)+'</div><div style="margin-top:8px;color:#ffcf5a;font-weight:800;font-size:13px">Winner gets '+CUR.reward+' &#129718; Feathers</div></div>';
 h+='<label style="display:block;background:linear-gradient(135deg,#8a5cff,#5a2ee0);color:#fff;text-align:center;font-weight:800;border-radius:12px;padding:13px;cursor:pointer">&#128247; Upload a clip (max '+MAXLEN+'s)<input id="chFile" type="file" accept="video/*" style="display:none"></label><div id="chTrim"></div><div id="chStat" style="text-align:center;color:#b9a88a;font-size:12px;min-height:16px;margin:8px 0 12px"></div><div style="color:#fff;font-weight:800;font-size:14px;margin:4px 2px 10px">Entries ('+SUBS.length+')</div>';
 if(!SUBS.length)h+='<div style="color:#8a795c;text-align:center;padding:14px 0">Be the first to enter!</div>';
 h+=sorted.map(function(s,i){var liked=MINE[s.id];return '<div style="background:#141017;border:1px solid #2a2233;border-radius:14px;overflow:hidden;margin-bottom:12px">'+(i<3?'<div style="background:#2a1f00;color:#ffcf5a;font-size:11px;font-weight:800;padding:4px 10px">Leaderboard #'+(i+1)+'</div>':'')+'<video src="'+esc(s.video_url)+'" controls playsinline preload="metadata" style="width:100%;max-height:56vh;background:#000;display:block"></video><div style="padding:10px 12px"><div style="font-weight:700;color:#fff;font-size:13px">@'+esc(s.name)+'</div>'+(s.caption?'<div style="color:#cbb9a0;font-size:12.5px;margin-top:2px">'+esc(s.caption)+'</div>':'')+'<button class="chLike" data-id="'+s.id+'" style="margin-top:8px;background:'+(liked?'#e0245e':'#241a2a')+';color:#fff;border:0;border-radius:999px;font-weight:800;font-size:13px;padding:7px 14px">&#10084; '+lc(s.id)+'</button></div></div>';}).join('');
 return h;}
function chalBind(){var f=document.getElementById('chFile');if(f)f.onchange=function(){chalTrim(f.files[0]);};[].forEach.call(ov.querySelectorAll('.chLike'),function(b){b.onclick=function(){chalLike(+b.getAttribute('data-id'));};});}
function chalStat(t){var s=document.getElementById('chStat');if(s)s.textContent=t;}
function chExt(f){return (f.name&&f.name.split('.').pop()||'mp4').toLowerCase();}
function chalTrim(file){if(!file||!CUR)return;var box=document.getElementById('chTrim');if(!box)return;var v=document.createElement('video');v.src=URL.createObjectURL(file);v.playsInline=true;v.style.cssText='width:100%;max-height:40vh;background:#000;border-radius:10px;margin-top:10px';box.innerHTML='';box.appendChild(v);var ui=document.createElement('div');ui.style.cssText='margin-top:8px';box.appendChild(ui);v.onloadedmetadata=function(){var dur=v.duration||0;var start=0;var len=Math.min(MAXLEN,Math.max(1,Math.floor(dur)));ui.innerHTML='<div style="color:#cbb9a0;font-size:12px;margin-bottom:4px">Start <span id="chS">0</span>s &#183; Length <span id="chL">'+len+'</span>s (max '+MAXLEN+')</div><input id="chStart" type="range" min="0" max="'+Math.max(0,Math.floor(dur-1))+'" value="0" step="1" style="width:100%"><input id="chLen" type="range" min="1" max="'+MAXLEN+'" value="'+len+'" step="1" style="width:100%"><button id="chGo" style="margin-top:8px;width:100%;background:#20a760;color:#fff;border:0;border-radius:10px;font-weight:800;padding:11px">Use this clip</button>';var sEl=ui.querySelector('#chStart'),lEl=ui.querySelector('#chLen');function upd(){start=+sEl.value;len=Math.min(+lEl.value,Math.max(1,Math.floor(dur-start)));document.getElementById('chS').textContent=start;document.getElementById('chL').textContent=len;try{v.currentTime=start;}catch(e){}}sEl.oninput=upd;lEl.oninput=upd;upd();ui.querySelector('#chGo').onclick=function(){chalRec(file,v,start,len,dur);};};}
function chalRec(file,v,start,len,dur){var uu=u();if(!uu){chalStat('Log in first');return;}var cap=prompt('Caption (optional):')||'';chalStat('Processing...');var full=(start<=0&&len>=Math.floor(dur));if(full&&file.size<=78643200){chalUp(file,chExt(file),cap);return;}try{v.currentTime=start;v.onseeked=function(){v.onseeked=null;var stream=v.captureStream?v.captureStream():(v.mozCaptureStream?v.mozCaptureStream():null);if(!stream){chalUp(file,chExt(file),cap);return;}var chk=[];var rec;try{rec=new MediaRecorder(stream,{mimeType:'video/webm'});}catch(e){try{rec=new MediaRecorder(stream);}catch(e2){chalUp(file,chExt(file),cap);return;}}rec.ondataavailable=function(e){if(e.data&&e.data.size)chk.push(e.data);};rec.onstop=function(){chalUp(new Blob(chk,{type:'video/webm'}),'webm',cap);};v.muted=false;v.play();rec.start();setTimeout(function(){try{rec.stop();}catch(e){}v.pause();},len*1000);};}catch(e){chalUp(file,chExt(file),cap);}}
function chalUp(fb,ext,cap){if(fb.size>78643200){chalStat('Too big (max 75MB)');return;}var uu=u();var path=CUR.id+'/'+uu+'-'+Date.now()+'.'+ext;chalStat('Uploading...');sb().storage.from('challenges').upload(path,fb,{contentType:ext==='webm'?'video/webm':(fb.type||'video/mp4')}).then(function(r){if(r.error){chalStat('Upload failed');return;}var url=sb().storage.from('challenges').getPublicUrl(path).data.publicUrl;return sb().from('flap_challenge_subs').insert({challenge_id:CUR.id,name:uu,video_url:url,caption:cap}).then(function(r2){if(r2.error){chalStat('Save failed');return;}chalStat('Posted! Good luck.');chalLoad();});}).catch(function(e){chalStat('Error');});}
function chalLike(id){var uu=u();if(!uu||MINE[id])return;MINE[id]=1;LIKES[id]=(LIKES[id]||0)+1;if(TAB==='chal')render();sb().from('flap_challenge_likes').insert({sub_id:id,name:uu}).then(function(){});}
function chalLoad(){var c=sb();if(!c)return;c.from('flap_challenges').select('*').eq('status','open').order('id',{ascending:false}).limit(1).then(function(r){CUR=(r.data&&r.data[0])||null;if(!CUR){if(TAB==='chal')render();return;}c.from('flap_challenge_subs').select('*').eq('challenge_id',CUR.id).then(function(r2){SUBS=r2.data||[];var ids=SUBS.map(function(s){return s.id;});LIKES={};MINE={};if(!ids.length){if(TAB==='chal')render();return;}c.from('flap_challenge_likes').select('sub_id,name').in('sub_id',ids).then(function(r3){var uu=u();(r3.data||[]).forEach(function(l){LIKES[l.sub_id]=(LIKES[l.sub_id]||0)+1;if(l.name===uu)MINE[l.sub_id]=1;});if(TAB==='chal')render();});});});}
function storeHtml(){var h='<button id="fcGF" style="width:100%;margin:0 0 6px;background:linear-gradient(135deg,#ffb44a,#f0891c);color:#fff;border:0;border-radius:12px;font-weight:800;font-size:15px;padding:13px;box-shadow:0 3px 0 #c9740a">&#129718; Get Feathers &#8212; buy a pack</button><div style="text-align:center;color:#8a795c;font-size:12px;margin:2px 0 12px">Buy with Feathers, then Equip to use it.</div>';
 CATS.forEach(function(cat){var items=ITEMS.filter(function(x){return x.category===cat;});if(!items.length)return;h+='<div style="color:#cbb98f;font-weight:800;font-size:13px;margin:14px 2px 8px">'+cat+'</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">';
  h+=items.map(function(x){var owned=OWNED[x.item];var eq=EQUIP[cat]===x.item;var fx=FX[x.item];var demo=fx?'<span class="'+fx+'" style="font-weight:800;font-size:18px">Name</span>':'<span style="font-size:26px">'+(EMO[x.item]||'&#129718;')+'</span>';var btn;
   if(!owned)btn='<button class="fcBuy" data-item="'+x.item+'" style="width:100%;background:#f0891c;color:#fff;border:0;border-radius:999px;font-weight:800;font-size:12px;padding:7px;box-shadow:0 3px 0 #c9740a">Unlock &#183; '+x.price+' &#129718;</button>';
   else if(eq)btn='<button class="fcUn" data-slot="'+cat+'" style="width:100%;background:#3a2b6e;color:#fff;border:0;border-radius:999px;font-weight:800;font-size:11px;padding:7px">Equipped &#10003; Remove</button>';
   else btn='<button class="fcEq" data-item="'+x.item+'" style="width:100%;background:#20a760;color:#fff;border:0;border-radius:999px;font-weight:800;font-size:12px;padding:7px">Equip</button>';
   return '<div style="background:#141017;border:1px solid '+(eq?'#ffcf5a':'#2a2233')+';border-radius:14px;padding:12px 10px;text-align:center"><div style="min-height:30px;display:grid;place-items:center">'+demo+'</div><div style="color:#fff;font-weight:700;font-size:13px;margin:6px 0 8px">'+esc(x.label)+'</div>'+btn+'</div>';
  }).join('');h+='</div>';});
 return h;}
function storeBind(){var g=document.getElementById('fcGF');if(g)g.onclick=gfOpen;[].forEach.call(ov.querySelectorAll('.fcBuy'),function(b){b.onclick=function(){buy(b.getAttribute('data-item'),b);};});[].forEach.call(ov.querySelectorAll('.fcEq'),function(b){b.onclick=function(){equip(b.getAttribute('data-item'));};});[].forEach.call(ov.querySelectorAll('.fcUn'),function(b){b.onclick=function(){unequip(b.getAttribute('data-slot'));};});}
function buy(item,btn){var uu=u();if(!uu){alert('Log in first');return;}btn.disabled=true;btn.innerHTML='...';sb().rpc('feather_buy',{p_name:uu,p_item:item}).then(function(r){if(!(r.data&&r.data.ok)){var m=(r.data&&r.data.error)||'error';alert(m==='not enough'?'Not enough Feathers. Tap Get Feathers to top up.':'Failed: '+m);if(TAB==='store')render();return;}OWNED[item]=1;if(r.data.balance!=null)BAL=r.data.balance;if(TAB==='store')render();});}
function equip(item){var uu=u();sb().rpc('feather_equip',{p_name:uu,p_item:item}).then(function(r){if(r.data&&r.data.ok){EQUIP[r.data.slot]=item;applyCos();if(TAB==='store')render();}else alert('Equip failed');});}
function unequip(slot){var uu=u();sb().rpc('feather_unequip',{p_name:uu,p_slot:slot}).then(function(){delete EQUIP[slot];applyCos();if(TAB==='store')render();});}
function applyCos(){var uu=u();if(!uu)return;var it=EQUIP['Names'];var fx=it?FX[it]:null;var all=document.querySelectorAll('b,strong,span,a,div');[].forEach.call(all,function(e){if(e.children.length===0){var t=(e.textContent||'').trim();if(t===uu&&t.length>0&&t.length<40&&!e.closest('#fcs2')){Object.keys(FX).forEach(function(k){e.classList.remove(FX[k]);});if(fx)e.classList.add(fx);}}});}
var _to;var mo=new MutationObserver(function(){clearTimeout(_to);_to=setTimeout(applyCos,400);});try{mo.observe(document.body,{childList:true,subtree:true});}catch(e){}
function gfLink(s){return 'https://whop.com/theflap/'+s+'?metadata[theflap_username]='+encodeURIComponent(u());}
var gf=document.createElement('div');gf.style.cssText='position:fixed;inset:0;z-index:2147483600;background:rgba(0,0,0,.6);display:none;align-items:flex-end;justify-content:center';
function gfPack(a,bo,tag,pr,sl){var t=tag==='pop'?'<span style="position:absolute;top:-8px;left:50%;transform:translateX(-50%);background:#f0891c;color:#fff;font-weight:800;font-size:9.5px;padding:2px 9px;border-radius:999px;white-space:nowrap">&#11088; POPULAR</span>':(tag==='deal'?'<span style="position:absolute;top:-8px;left:50%;transform:translateX(-50%);background:#ffc53a;color:#3a2600;font-weight:800;font-size:9.5px;padding:2px 9px;border-radius:999px;white-space:nowrap">&#128293; BEST DEAL</span>':'');return '<div style="background:#fffdf8;border:'+(tag==='deal'?'2px solid #ffc53a':'1px solid #eadcc4')+';border-radius:15px;padding:13px 10px 11px;text-align:center;position:relative;color:#2a2016">'+t+'<div style="font-size:26px">&#129718;</div><div style="font-weight:800;font-size:18px;margin-top:3px">'+a+'<small style="display:block;font-size:10px;color:#8a795c;font-weight:700">FEATHERS</small></div><div style="display:inline-block;background:#e9faef;color:#20a760;border:1px solid #b6e8c6;border-radius:999px;font-size:10px;font-weight:700;padding:1px 7px;margin:5px 0 7px;'+(bo?'':'visibility:hidden')+'">'+(bo||'.')+'</div><a href="'+gfLink(sl)+'" target="_blank" rel="noopener" style="display:block;border-radius:10px;background:#f0891c;color:#fff;font-weight:800;font-size:14px;padding:9px;text-decoration:none;box-shadow:0 3px 0 #c9740a">'+pr+'</a></div>';}
function gfHtml(){return '<div style="width:100%;max-width:460px;max-height:94vh;overflow:auto;background:linear-gradient(180deg,#241a10,#191009);border:1px solid #3a2c18;border-top-left-radius:22px;border-top-right-radius:22px;color:#eee;font-family:inherit"><div style="display:flex;align-items:center;gap:10px;padding:14px 16px;border-bottom:1px solid #3a2c18;background:linear-gradient(90deg,#2a2016,#1d140b);position:sticky;top:0"><span style="width:34px;height:34px;border-radius:50%;background:radial-gradient(circle at 35% 30%,#fff2c0,#f0b400 60%,#c98a00);display:grid;place-items:center;font-size:18px">&#129718;</span><b style="font-size:17px;color:#fff">Get Feathers</b><button id="gfX" style="margin-left:auto;background:0;border:0;color:#cbb98f;font-size:24px">&times;</button></div><div style="padding:14px"><div style="background:#2a2016;border:1px dashed #6b5222;border-radius:12px;padding:9px 12px;font-size:12.5px;color:#e7c98c;margin-bottom:14px">Buying as <b style="color:#fff">@'+esc(u()||'you')+'</b> &#8212; Feathers land on your account automatically.</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">'+gfPack('500','',null,'$1.99','500-feathers')+gfPack('1,500','+7% more','pop','$4.99','1500-feathers')+gfPack('4,000','+15% more','deal','$9.99','4-000-feathers')+gfPack('12,000','+25% more',null,'$24.99','12-000-feathers')+'</div><a href="'+gfLink('theflap-premium')+'" target="_blank" rel="noopener" style="display:block;text-decoration:none;margin-top:16px;background:linear-gradient(135deg,#3a2b6e,#7a52c8);border-radius:14px;padding:14px;color:#fff"><div style="font-weight:800;font-size:15px">&#128081; TheFlap Premium &#8212; $4.99/mo</div></a></div></div>';}
function gfOpen(){gf.innerHTML=gfHtml();gf.style.display='flex';var x=document.getElementById('gfX');if(x)x.onclick=function(){gf.style.display='none';};}
gf.onclick=function(e){if(e.target===gf)gf.style.display='none';};
window.flapGetFeathers=gfOpen;
function takeover(){try{window.nxOpen=function(){open();};}catch(e){}var T=String.fromCharCode(55356,57286);var bs=[].slice.call(document.querySelectorAll('button'));for(var i=0;i<bs.length;i++){var b=bs[i];try{if(getComputedStyle(b).position==='fixed'){var t=(b.textContent||'').trim();if(t.indexOf(T)>-1&&t.length<=3&&!b.__fc){b.__fc=1;b.addEventListener('click',function(e){e.stopImmediatePropagation();e.preventDefault();open();},true);}}}catch(e){}}}
function mount(){if(document.body){document.body.appendChild(ov);document.body.appendChild(gf);}takeover();}
if(document.body)mount();else document.addEventListener('DOMContentLoaded',mount);
var tr=0;var iv=setInterval(function(){tr++;takeover();if(tr>25)clearInterval(iv);},500);
try{if(/[?&]go=challenge/.test(location.search)||location.hash==='#challenge'){setTimeout(open,900);}}catch(e){}
})();
